# Generated by Django 5.0.7 on 2024-07-20 15:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('bio', models.TextField(blank=True, null=True)),
                ('course', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=6)),
                ('phone_number', models.CharField(max_length=20)),
                ('national_id', models.PositiveBigIntegerField(unique=True)),
                ('account_number', models.PositiveIntegerField(unique=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('department', models.CharField(max_length=30)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='classroom.classroom')),
            ],
        ),
    ]
