# Generated by Django 5.0.7 on 2024-07-20 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('course_code', models.CharField(max_length=5, unique=True)),
                ('content', models.TextField()),
                ('start_date', models.DateField(verbose_name=datetime.date.today)),
                ('end_date', models.DateField(verbose_name=datetime.date.today)),
                ('course_duration', models.DurationField(default=1)),
                ('department', models.CharField(max_length=30)),
                ('number_of_students', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
