# Generated by Django 5.0.7 on 2024-09-04 17:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_class', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('course_code', models.CharField(max_length=5, unique=True)),
                ('content', models.TextField()),
                ('start_date', models.DateField(verbose_name=datetime.date.today)),
                ('end_date', models.DateField(verbose_name=datetime.date.today)),
                ('course_duration', models.DurationField(default=1)),
                ('department', models.CharField(max_length=30)),
                ('number_of_students', models.PositiveSmallIntegerField(default=0)),
                ('classes', models.ManyToManyField(related_name='courses', to='student_class.student_class')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='teacher.teacher')),
            ],
        ),
    ]
