# Generated by Django 5.0.7 on 2024-09-04 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('student_class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPeriod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='name', max_length=30)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days_of_the_week', models.CharField(default='Monday', max_length=10, null=True)),
                ('created_at', models.DateField(default='2024-08-10')),
                ('updated_at', models.DateField(default='2024-08-10')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class', to='course.course')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='student_class.student_class')),
            ],
        ),
    ]
