# Generated by Django 5.0.7 on 2024-07-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperiod',
            name='days_of_the_week',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default='Monday', max_length=10),
        ),
    ]
