# Generated by Django 5.0.7 on 2024-07-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0002_alter_classperiod_days_of_the_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperiod',
            name='days_of_the_week',
            field=models.CharField(default='Monday', max_length=10, null=True),
        ),
    ]
