# Generated by Django 5.0.7 on 2024-07-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('classroom_id', models.PositiveIntegerField()),
                ('description', models.TextField(null=True)),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('equipments', models.TextField()),
            ],
        ),
    ]
