# Generated by Django 5.0.7 on 2024-07-20 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('date_of_birth', models.DateTimeField(verbose_name=datetime.date.today)),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('country', models.CharField(max_length=20)),
                ('profile', models.ImageField(null=True, upload_to='')),
                ('student_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=6)),
                ('bio', models.TextField(null=True)),
                ('national_id', models.IntegerField(default=0)),
                ('joining_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('parent', models.CharField(max_length=50)),
                ('next_of_kin', models.CharField(max_length=50)),
                ('parent_number', models.CharField(max_length=15)),
            ],
        ),
    ]
