# Generated by Django 5.0.7 on 2024-09-04 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('student_class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('date_of_birth', models.DateField()),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('country', models.CharField(max_length=20)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='student_pictures/')),
                ('student_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=6)),
                ('bio', models.TextField(null=True)),
                ('national_id', models.IntegerField(default=0)),
                ('enrollment_date', models.DateField()),
                ('end_date', models.DateField()),
                ('parent', models.CharField(max_length=50)),
                ('next_of_kin', models.CharField(max_length=50)),
                ('parent_number', models.CharField(max_length=15)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_enrolled', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student_class.student_class')),
                ('courses', models.ManyToManyField(to='course.course')),
            ],
        ),
    ]
