# Generated by Django 5.0.7 on 2024-07-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_date_of_birth_alter_student_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='joining_date',
            field=models.DateField(),
        ),
    ]
